-- MySQL Script generated by MySQL Workbench
-- Thu Mar  9 12:45:33 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BancoDB
-- -----------------------------------------------------
-- Base de datos para el sistema web de gestión bancaria.

-- -----------------------------------------------------
-- Schema BancoDB
--
-- Base de datos para el sistema web de gestión bancaria.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BancoDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `BancoDB` ;

-- -----------------------------------------------------
-- Table `BancoDB`.`Asistente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BancoDB`.`Asistente` ;

CREATE TABLE IF NOT EXISTS `BancoDB`.`Asistente` (
  `NIF` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`NIF`),
  CONSTRAINT `Persona_FK`
    FOREIGN KEY (`NIF`)
    REFERENCES `BancoDB`.`Persona` (`NIF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoDB`.`Autorizado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BancoDB`.`Autorizado` ;

CREATE TABLE IF NOT EXISTS `BancoDB`.`Autorizado` (
  `Persona` VARCHAR(10) NOT NULL,
  `Empresa` INT NOT NULL,
  PRIMARY KEY (`Persona`),
  INDEX `Empresa_FK_idx` (`Empresa` ASC) VISIBLE,
  CONSTRAINT `Persona_FK`
    FOREIGN KEY ()
    REFERENCES `BancoDB`.`Persona` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Empresa_FK`
    FOREIGN KEY (`Empresa`)
    REFERENCES `BancoDB`.`Empresa` (`CIF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoDB`.`CambDivisa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BancoDB`.`CambDivisa` ;

CREATE TABLE IF NOT EXISTS `BancoDB`.`CambDivisa` (
  `Operacion` INT NOT NULL,
  `origen` VARCHAR(45) NOT NULL,
  `destino` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Operacion`),
  CONSTRAINT `Operacion_FK`
    FOREIGN KEY (`Operacion`)
    REFERENCES `BancoDB`.`Operacion` (`idOperacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoDB`.`Chat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BancoDB`.`Chat` ;

CREATE TABLE IF NOT EXISTS `BancoDB`.`Chat` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Asistente_NIF` VARCHAR(10) NOT NULL,
  `Cliente_ID_Cliente` INT NOT NULL,
  INDEX `fk_Asistente_has_Cliente_Cliente1_idx` (`Cliente_ID_Cliente` ASC) VISIBLE,
  INDEX `fk_Asistente_has_Cliente_Asistente1_idx` (`Asistente_NIF` ASC) VISIBLE,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_Asistente_has_Cliente_Asistente1`
    FOREIGN KEY (`Asistente_NIF`)
    REFERENCES `BancoDB`.`Asistente` (`NIF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asistente_has_Cliente_Cliente1`
    FOREIGN KEY (`Cliente_ID_Cliente`)
    REFERENCES `BancoDB`.`Cliente` (`ID_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoDB`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BancoDB`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `BancoDB`.`Cliente` (
  `ID_Cliente` INT NOT NULL,
  `Direcc` VARCHAR(45) NOT NULL,
  `Direccion` INT NOT NULL,
  PRIMARY KEY (`ID_Cliente`),
  INDEX `Direccion_FK_idx` (`Direccion` ASC) VISIBLE,
  CONSTRAINT `Direccion_FK`
    FOREIGN KEY (`Direccion`)
    REFERENCES `BancoDB`.`Direccion` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoDB`.`Cuenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BancoDB`.`Cuenta` ;

CREATE TABLE IF NOT EXISTS `BancoDB`.`Cuenta` (
  `numCuenta` INT NOT NULL,
  `cliente` INT NOT NULL,
  `saldo` FLOAT NULL,
  PRIMARY KEY (`numCuenta`),
  CONSTRAINT `Cliente_FK`
    FOREIGN KEY (`cliente`)
    REFERENCES `BancoDB`.`Cliente` (`ID_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoDB`.`Direccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BancoDB`.`Direccion` ;

CREATE TABLE IF NOT EXISTS `BancoDB`.`Direccion` (
  `ID` INT NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `planta_puerta_oficina` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `region` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NOT NULL,
  `codPostal` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `UNIQUE_values` (`calle` ASC, `numero` ASC, `planta_puerta_oficina` ASC, `codPostal` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoDB`.`Empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BancoDB`.`Empresa` ;

CREATE TABLE IF NOT EXISTS `BancoDB`.`Empresa` (
  `CIF` INT NOT NULL,
  `Cliente` INT NOT NULL,
  PRIMARY KEY (`CIF`, `Cliente`),
  UNIQUE INDEX `Cliente_UNIQUE` (`Cliente` ASC) VISIBLE,
  CONSTRAINT `Cliente_FK`
    FOREIGN KEY (`Cliente`)
    REFERENCES `BancoDB`.`Cliente` (`ID_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoDB`.`Extraccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BancoDB`.`Extraccion` ;

CREATE TABLE IF NOT EXISTS `BancoDB`.`Extraccion` (
  `Operacion` INT NOT NULL,
  `Cantidad` FLOAT NOT NULL,
  PRIMARY KEY (`Operacion`),
  CONSTRAINT `Operacion_FK`
    FOREIGN KEY (`Operacion`)
    REFERENCES `BancoDB`.`Operacion` (`idOperacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoDB`.`Gestor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BancoDB`.`Gestor` ;

CREATE TABLE IF NOT EXISTS `BancoDB`.`Gestor` (
  `NIF` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`NIF`),
  CONSTRAINT `Persona_FK`
    FOREIGN KEY (`NIF`)
    REFERENCES `BancoDB`.`Persona` (`NIF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoDB`.`Mensaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BancoDB`.`Mensaje` ;

CREATE TABLE IF NOT EXISTS `BancoDB`.`Mensaje` (
  `ID_mensaje` INT NOT NULL AUTO_INCREMENT,
  `Fecha_hora` DATE NOT NULL,
  `chat` INT NOT NULL,
  `Contenido` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`ID_mensaje`),
  INDEX `chat_FK_idx` (`chat` ASC) VISIBLE,
  CONSTRAINT `chat_FK`
    FOREIGN KEY (`chat`)
    REFERENCES `BancoDB`.`Chat` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoDB`.`Operacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BancoDB`.`Operacion` ;

CREATE TABLE IF NOT EXISTS `BancoDB`.`Operacion` (
  `idOperacion` INT NOT NULL,
  `CuentaRealiza` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  PRIMARY KEY (`idOperacion`),
  INDEX `Cuenta_FK_idx` (`CuentaRealiza` ASC) VISIBLE,
  CONSTRAINT `Cuenta_FK`
    FOREIGN KEY (`CuentaRealiza`)
    REFERENCES `BancoDB`.`Cuenta` (`numCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoDB`.`Particular`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BancoDB`.`Particular` ;

CREATE TABLE IF NOT EXISTS `BancoDB`.`Particular` (
  `persona` VARCHAR(10) NOT NULL,
  `Cliente` INT NOT NULL,
  `Persona` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`persona`, `Cliente`, `Persona`),
  UNIQUE INDEX `Cliente_UNIQUE` (`Cliente` ASC) VISIBLE,
  UNIQUE INDEX `Persona_UNIQUE` (`Persona` ASC) VISIBLE,
  CONSTRAINT `Cliente_FK`
    FOREIGN KEY (`Cliente`)
    REFERENCES `BancoDB`.`Cliente` (`ID_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Persona_FK`
    FOREIGN KEY (`Persona`)
    REFERENCES `BancoDB`.`Persona` (`NIF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoDB`.`Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BancoDB`.`Persona` ;

CREATE TABLE IF NOT EXISTS `BancoDB`.`Persona` (
  `NIF` VARCHAR(10) NOT NULL,
  `primerNombre` VARCHAR(45) NOT NULL,
  `segundoNombre` VARCHAR(45) NULL,
  `primerApellido` VARCHAR(45) NOT NULL,
  `segundoApellido` VARCHAR(45) NULL,
  `fechaNacimiento` DATE NOT NULL,
  PRIMARY KEY (`NIF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoDB`.`Socio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BancoDB`.`Socio` ;

CREATE TABLE IF NOT EXISTS `BancoDB`.`Socio` (
  `persona` VARCHAR(10) NOT NULL,
  `Direccion` INT NOT NULL,
  `Empresa` INT NOT NULL,
  PRIMARY KEY (`persona`),
  UNIQUE INDEX `persona_UNIQUE` (`persona` ASC) VISIBLE,
  INDEX `Direccion_FK_idx` (`Direccion` ASC) VISIBLE,
  INDEX `Empresa_FK_idx` (`Empresa` ASC) VISIBLE,
  CONSTRAINT `Persona_FK`
    FOREIGN KEY (`persona`)
    REFERENCES `BancoDB`.`Persona` (`NIF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Direccion_FK`
    FOREIGN KEY (`Direccion`)
    REFERENCES `BancoDB`.`Direccion` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Empresa_FK`
    FOREIGN KEY (`Empresa`)
    REFERENCES `BancoDB`.`Empresa` (`CIF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoDB`.`Transferencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BancoDB`.`Transferencia` ;

CREATE TABLE IF NOT EXISTS `BancoDB`.`Transferencia` (
  `Operacion` INT NOT NULL,
  `CuentaDestion` INT NOT NULL,
  `cantidad` FLOAT NOT NULL,
  PRIMARY KEY (`Operacion`),
  INDEX `CuentaDestino_idx` (`CuentaDestion` ASC) VISIBLE,
  CONSTRAINT `Operacion`
    FOREIGN KEY (`Operacion`)
    REFERENCES `BancoDB`.`Operacion` (`idOperacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CuentaDestino`
    FOREIGN KEY (`CuentaDestion`)
    REFERENCES `BancoDB`.`Cuenta` (`numCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
