-- MySQL Script generated by MySQL Workbench
-- Sun Mar 19 21:51:16 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BancoDB
-- -----------------------------------------------------
-- Base de datos para el sistema web de gestión bancaria.

-- -----------------------------------------------------
-- Schema BancoDB
--
-- Base de datos para el sistema web de gestión bancaria.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BancoDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `BancoDB` ;

-- -----------------------------------------------------
-- Table `BancoDB`.`Asistente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BancoDB`.`Asistente` ;

CREATE TABLE IF NOT EXISTS `BancoDB`.`Asistente` (
  `ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `Usuario_FK`
    FOREIGN KEY (`ID`)
    REFERENCES `BancoDB`.`Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoDB`.`Autorizado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BancoDB`.`Autorizado` ;

CREATE TABLE IF NOT EXISTS `BancoDB`.`Autorizado` (
  `Usuario` INT NOT NULL,
  `Empresa` INT NOT NULL,
  PRIMARY KEY (`Usuario`),
  INDEX `Empresa_FK_idx` (`Empresa` ASC),
  CONSTRAINT `Usuario_FK`
    FOREIGN KEY (`Usuario`)
    REFERENCES `BancoDB`.`Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Empresa_FK`
    FOREIGN KEY (`Empresa`)
    REFERENCES `BancoDB`.`Empresa` (`CIF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoDB`.`CambDivisa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BancoDB`.`CambDivisa` ;

CREATE TABLE IF NOT EXISTS `BancoDB`.`CambDivisa` (
  `Operacion` INT NOT NULL,
  `origen` VARCHAR(45) NOT NULL,
  `destino` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Operacion`),
  CONSTRAINT `Operacion_FK`
    FOREIGN KEY (`Operacion`)
    REFERENCES `BancoDB`.`Operacion` (`idOperacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoDB`.`Chat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BancoDB`.`Chat` ;

CREATE TABLE IF NOT EXISTS `BancoDB`.`Chat` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Asistente_ID` INT NOT NULL,
  `Cliente_ID_Cliente` INT NOT NULL,
  INDEX `fk_Asistente_has_Cliente_Cliente1_idx` (`Cliente_ID_Cliente` ASC),
  INDEX `fk_Asistente_has_Cliente_Asistente1_idx` (`Asistente_ID` ASC),
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_Asistente_has_Cliente_Asistente1`
    FOREIGN KEY (`Asistente_ID`)
    REFERENCES `BancoDB`.`Asistente` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asistente_has_Cliente_Cliente1`
    FOREIGN KEY (`Cliente_ID_Cliente`)
    REFERENCES `BancoDB`.`Cliente` (`ID_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoDB`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BancoDB`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `BancoDB`.`Cliente` (
  `ID_Cliente` INT NOT NULL,
  `Direcc` VARCHAR(45) NOT NULL,
  `Direccion` INT NOT NULL,
  PRIMARY KEY (`ID_Cliente`),
  INDEX `Direccion_FK_idx` (`Direccion` ASC),
  CONSTRAINT `Direccion_FK`
    FOREIGN KEY (`Direccion`)
    REFERENCES `BancoDB`.`Direccion` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoDB`.`Cuenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BancoDB`.`Cuenta` ;

CREATE TABLE IF NOT EXISTS `BancoDB`.`Cuenta` (
  `numCuenta` INT NOT NULL,
  `cliente` INT NOT NULL,
  `saldo` FLOAT NULL,
  PRIMARY KEY (`numCuenta`),
  CONSTRAINT `Cliente_FK`
    FOREIGN KEY (`cliente`)
    REFERENCES `BancoDB`.`Cliente` (`ID_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoDB`.`Direccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BancoDB`.`Direccion` ;

CREATE TABLE IF NOT EXISTS `BancoDB`.`Direccion` (
  `ID` INT NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `planta_puerta_oficina` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `region` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NOT NULL,
  `codPostal` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `UNIQUE_values` (`calle` ASC, `numero` ASC, `planta_puerta_oficina` ASC, `codPostal` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoDB`.`Empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BancoDB`.`Empresa` ;

CREATE TABLE IF NOT EXISTS `BancoDB`.`Empresa` (
  `CIF` INT NOT NULL,
  `Cliente` INT NOT NULL,
  PRIMARY KEY (`CIF`, `Cliente`),
  UNIQUE INDEX `Cliente_UNIQUE` (`Cliente` ASC),
  CONSTRAINT `Cliente_FK`
    FOREIGN KEY (`Cliente`)
    REFERENCES `BancoDB`.`Cliente` (`ID_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoDB`.`Extraccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BancoDB`.`Extraccion` ;

CREATE TABLE IF NOT EXISTS `BancoDB`.`Extraccion` (
  `Operacion` INT NOT NULL,
  `Cantidad` FLOAT NOT NULL,
  PRIMARY KEY (`Operacion`),
  CONSTRAINT `Operacion_FK`
    FOREIGN KEY (`Operacion`)
    REFERENCES `BancoDB`.`Operacion` (`idOperacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoDB`.`Gestor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BancoDB`.`Gestor` ;

CREATE TABLE IF NOT EXISTS `BancoDB`.`Gestor` (
  `ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `Usuario_FK`
    FOREIGN KEY (`ID`)
    REFERENCES `BancoDB`.`Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoDB`.`Mensaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BancoDB`.`Mensaje` ;

CREATE TABLE IF NOT EXISTS `BancoDB`.`Mensaje` (
  `ID_mensaje` INT NOT NULL AUTO_INCREMENT,
  `Fecha_hora` DATE NOT NULL,
  `chat` INT NOT NULL,
  `Contenido` VARCHAR(500) NOT NULL,
  `emisor` INT NOT NULL,
  PRIMARY KEY (`ID_mensaje`),
  INDEX `chat_FK_idx` (`chat` ASC),
  INDEX `emisor_FK_idx` (`emisor` ASC),
  CONSTRAINT `chat_FK`
    FOREIGN KEY (`chat`)
    REFERENCES `BancoDB`.`Chat` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `emisor_FK`
    FOREIGN KEY (`emisor`)
    REFERENCES `BancoDB`.`Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoDB`.`Operacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BancoDB`.`Operacion` ;

CREATE TABLE IF NOT EXISTS `BancoDB`.`Operacion` (
  `idOperacion` INT NOT NULL,
  `CuentaRealiza` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  PRIMARY KEY (`idOperacion`),
  INDEX `Cuenta_FK_idx` (`CuentaRealiza` ASC),
  CONSTRAINT `Cuenta_FK`
    FOREIGN KEY (`CuentaRealiza`)
    REFERENCES `BancoDB`.`Cuenta` (`numCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoDB`.`Particular`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BancoDB`.`Particular` ;

CREATE TABLE IF NOT EXISTS `BancoDB`.`Particular` (
  `Persona` INT NOT NULL,
  `Cliente` INT NOT NULL,
  PRIMARY KEY (`Persona`, `Cliente`),
  UNIQUE INDEX `Cliente_UNIQUE` (`Cliente` ASC),
  UNIQUE INDEX `Persona_UNIQUE` (`Persona` ASC),
  CONSTRAINT `Cliente_FK`
    FOREIGN KEY (`Cliente`)
    REFERENCES `BancoDB`.`Cliente` (`ID_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Usuario_FK`
    FOREIGN KEY (`Persona`)
    REFERENCES `BancoDB`.`Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoDB`.`Rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BancoDB`.`Rol` ;

CREATE TABLE IF NOT EXISTS `BancoDB`.`Rol` (
  `idRol` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRol`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoDB`.`RolUsuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BancoDB`.`RolUsuario` ;

CREATE TABLE IF NOT EXISTS `BancoDB`.`RolUsuario` (
  `idRol` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idRol`, `idUsuario`),
  INDEX `fk_idUsuario_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_idRol`
    FOREIGN KEY (`idRol`)
    REFERENCES `BancoDB`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `BancoDB`.`Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoDB`.`Socio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BancoDB`.`Socio` ;

CREATE TABLE IF NOT EXISTS `BancoDB`.`Socio` (
  `usuario` INT NOT NULL,
  `Direccion` INT NOT NULL,
  `Empresa` INT NOT NULL,
  PRIMARY KEY (`usuario`),
  UNIQUE INDEX `persona_UNIQUE` (`usuario` ASC),
  INDEX `Direccion_FK_idx` (`Direccion` ASC),
  INDEX `Empresa_FK_idx` (`Empresa` ASC),
  CONSTRAINT `Usuario_FK`
    FOREIGN KEY (`usuario`)
    REFERENCES `BancoDB`.`Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Direccion_FK`
    FOREIGN KEY (`Direccion`)
    REFERENCES `BancoDB`.`Direccion` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Empresa_FK`
    FOREIGN KEY (`Empresa`)
    REFERENCES `BancoDB`.`Empresa` (`CIF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoDB`.`Transferencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BancoDB`.`Transferencia` ;

CREATE TABLE IF NOT EXISTS `BancoDB`.`Transferencia` (
  `Operacion` INT NOT NULL,
  `CuentaDestion` INT NOT NULL,
  `cantidad` FLOAT NOT NULL,
  PRIMARY KEY (`Operacion`),
  INDEX `CuentaDestino_idx` (`CuentaDestion` ASC),
  CONSTRAINT `Operacion`
    FOREIGN KEY (`Operacion`)
    REFERENCES `BancoDB`.`Operacion` (`idOperacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CuentaDestino`
    FOREIGN KEY (`CuentaDestion`)
    REFERENCES `BancoDB`.`Cuenta` (`numCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoDB`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BancoDB`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `BancoDB`.`Usuario` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NIF` VARCHAR(10) NOT NULL,
  `primerNombre` VARCHAR(45) NOT NULL,
  `segundoNombre` VARCHAR(45) NULL,
  `primerApellido` VARCHAR(45) NOT NULL,
  `segundoApellido` VARCHAR(45) NULL,
  `fechaNacimiento` DATE NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
